# Generated by Django 6.0.4 on 2026-06-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='initials',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='authors',
            name='surname',
        ),
    ]
