# Generated by Django 6.0.4 on 2026-06-02 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_abstracttype_casereport'),
        ('authors', '0002_rename_initials_authors_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='casereport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='article.casereport'),
        ),
    ]
