# Generated by Django 6.0.4 on 2026-05-21 18:23

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0001_initial'),
        ('faculty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('presentername', models.CharField(max_length=200)),
                ('presenteremail', models.CharField(max_length=200)),
                ('presenterphone', models.CharField(max_length=200)),
                ('introduction', tinymce.models.HTMLField()),
                ('methods', tinymce.models.HTMLField()),
                ('results', tinymce.models.HTMLField()),
                ('conclusion', tinymce.models.HTMLField()),
                ('limitations', tinymce.models.HTMLField()),
                ('keywords', models.CharField(max_length=200)),
                ('frtitle', models.CharField(max_length=300)),
                ('frintroduction', tinymce.models.HTMLField()),
                ('frmethods', tinymce.models.HTMLField()),
                ('frresults', tinymce.models.HTMLField()),
                ('frconclusion', tinymce.models.HTMLField()),
                ('frlimitations', tinymce.models.HTMLField()),
                ('frkeywords', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('submitted_at', models.DateField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.conference')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.faculty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateField(auto_now_add=True)),
                ('submitted_at', models.DateField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', tinymce.models.HTMLField()),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('minor revision', 'Minor Revisions'), ('major revision', 'Major Revisions'), ('rejected', 'Rejected')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
