# Generated by Django 6.0.4 on 2026-06-01 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstracttype',
            field=models.CharField(choices=[('Case Report', 'Case Report'), ('Original/Review', 'Original/Review')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
