# Generated by Django 6.0.4 on 2026-06-01 12:17

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_abstracttype'),
        ('conference', '0001_initial'),
        ('faculty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstracttype',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Casereport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstracttype', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300, unique=True)),
                ('presentername', models.CharField(max_length=200)),
                ('presenteremail', models.CharField(max_length=200)),
                ('presenterphone', models.CharField(max_length=200)),
                ('casereport', tinymce.models.HTMLField()),
                ('keywords', models.CharField(max_length=200)),
                ('frtitle', models.CharField(max_length=300)),
                ('frcasereport', tinymce.models.HTMLField()),
                ('frkeywords', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('submitted_at', models.DateField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.conference')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.faculty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
