# Generated by Django 6.0.4 on 2026-06-03 10:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_abstracttype_casereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlereviewer',
            name='casereport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.casereport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='casereport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.casereport'),
            preserve_default=False,
        ),
    ]
