# Generated by Django 6.0.4 on 2026-04-27 16:20

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_comment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='introduction',
            field=tinymce.models.HTMLField(),
        ),
    ]
