# Generated by Django 6.0.4 on 2026-04-28 09:25

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('minor revision', 'Minor Revisions'), ('major revision', 'Major Revisions'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
