# Generated by Django 6.0.4 on 2026-06-04 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_articlereviewer_article_and_more'),
        ('reviewers', '0002_reviewer_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlereviewer',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlereviewer',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='articlereviewer',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewers.reviewer'),
        ),
    ]
