# Generated by Django 6.0.4 on 2026-06-05 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_articlereviewer_reviewed_articlereviewer_token_and_more'),
        ('reviewers', '0002_reviewer_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introductionscore', models.PositiveSmallIntegerField()),
                ('methodscore', models.PositiveSmallIntegerField()),
                ('resultscore', models.PositiveSmallIntegerField()),
                ('conclusionscore', models.PositiveSmallIntegerField()),
                ('overallscore', models.PositiveSmallIntegerField()),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('casereport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.casereport')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewers.reviewer')),
            ],
        ),
    ]
