# Generated by Django 6.0.4 on 2026-06-05 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_reviewerreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerreport',
            name='titlescore',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
