# Generated by Django 6.0.4 on 2026-06-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_reviewerreport_titlescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewerreport',
            name='conclusionscore',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='reviewerreport',
            name='introductionscore',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='reviewerreport',
            name='methodscore',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='reviewerreport',
            name='overallscore',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='reviewerreport',
            name='resultscore',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='reviewerreport',
            name='titlescore',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
