# Generated by Django 6.0.4 on 2026-06-06 08:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_alter_reviewerreport_conclusionscore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerreport',
            name='totalscore',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
