# Generated by Django 6.0.4 on 2026-06-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='usertype',
            field=models.CharField(default='reviewer', max_length=100),
        ),
    ]
